services:
  _defaults:
    autowire: true
    public: true
    autoconfigure: true

  # Custom regexp listener
  Markocupic\RszBenutzerverwaltungBundle\EventListener\ContaoHooks\AddCustomRegexpListener: ~

  # Custom regexp listener
  Markocupic\RszBenutzerverwaltungBundle\EventListener\ContaoHooks\CheckCredentialsListener: ~