services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true


  # Prepare export
  Markocupic\RszBenutzerverwaltungBundle\Excel\PrepareExportFromSession:
    public: true
    arguments:
    - '@database_connection'
    - '@session'