services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      $projectDir: '%kernel.project_dir%'
      $rszWettkampfkategorienMap: '%rsz_benutzerverwaltung.wettkampfkategorien%'

  Markocupic\RszBenutzerverwaltungBundle\:
    resource: ../src/
    exclude: [ '../src/{DependencyInjection}' ]

